name: tfg_grupo7
description: Nutritional tracking app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Persistencia
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2

  # Networking
  dio: ^5.4.1

  # UI & Charts
  fl_chart: ^0.68.0
  cached_network_image: ^3.3.1

  # Routing
  go_router: ^14.0.2

  # JSON
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Utils
  shared_preferences: ^2.2.2
  intl: ^0.19.0  # Para formateo de fechas

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  analyzer: ^5.13.0

  # Code generation
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11
  isar_generator: ^3.1.0+1